src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Product__c/Case_Product__c.object-meta.xml
<CustomObject>
    <label>Case Product</label>
    <nameField>
        <label>Case Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Product__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Return_percentage__c.field-meta.xml
<CustomField>
    <fullName>Return_percentage__c</fullName>
    <description>Enter percent of value you want to return to client.</description>
    <label>Return percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <label>Discount Percentage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Final_Price__c</fullName>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Discount__c/Order_Discount__c.object-meta.xml
<CustomObject>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Order Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Order Discounts</relationshipLabel>
    <relationshipName>Order_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Discount__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Discounts</relationshipLabel>
    <relationshipName>Order_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Actions/TA_Case_ApplyComplaintToOrder.cls
/**
 * Created by patryk.witkowski_bri on 5/27/2025.
 */

public with sharing class TA_Case_ApplyComplaintToOrder implements TriggerAction.AfterUpdate {
    public void afterUpdate(List<SObject> triggerNew, List<SObject> triggerOld) {
        //key is an ID OF case, value is a order id
        Map<Id, Id> orderMapCase = new Map<Id, Id>();
        for(Case caseItem : (List <Case>) triggerNew) {
            if(caseItem.Status.equalsIgnoreCase(Utils.CASES.STATUS.Closed) && caseItem.Order__c != null) {
                orderMapCase.put(caseItem.Id, caseItem.Order__c);
            }
        }

        if(orderMapCase.isEmpty()) {
            return;
        }

        List<Case_Product__c> caseProducts = [
                SELECT Id, Name, Case__c, Product__c, Return_percentage__c, Order_Product__c, Order_Product__r.OrderId, Order_Product__r.UnitPrice
                FROM Case_Product__c
                WHERE Case__c IN :orderMapCase.keySet() AND Status__c = :Utils.CASE_PRODUCT.STATUS.Approved
        ];

        if(caseProducts.isEmpty()) {
            throw new HandledException('No case products records');
        }

        Map<Id, Decimal> orderPriceAdjustments = new Map<Id, Decimal>();


        for(Case_Product__c cp : caseProducts) {
            Decimal adjustment = (cp.Order_Product__r.UnitPrice * (cp.Return_percentage__c / 100.0));
            Decimal currentAdjustment = orderPriceAdjustments.get(cp.Order_Product__r.OrderId) ?? 0;
            orderPriceAdjustments.put(cp.Order_Product__r.OrderId, currentAdjustment + adjustment);
        }
        //id of order and its list of discounts
        Map<Id, List<Decimal>> orderDiscountsMap = new Map<Id, List<Decimal>>();

        for(Order_Discount__c orderDiscount : [
                SELECT Order__c, Discount__r.Discount_Percentage__c, Discount__r.Discount_Amount__c
                FROM Order_Discount__c
                WHERE Order__c IN :orderPriceAdjustments.keySet()
        ]) {
            if(orderDiscountsMap.get(orderDiscount.Order__c) == null) {
                orderDiscountsMap.put(orderDiscount.Order__c, new List<Decimal>());
            }

            if(orderDiscount.Discount__r.Discount_Percentage__c != null) {
                orderDiscountsMap.get(orderDiscount.Order__c).add(orderDiscount.Discount__r.Discount_Percentage__c / 100);
            }

            if(orderDiscount.Discount__r.Discount_Amount__c != null) {
                orderDiscountsMap.get(orderDiscount.Order__c).add(orderDiscount.Discount__r.Discount_Amount__c);
            }
        }

        for (Id orderId : orderDiscountsMap.keySet()) {
            List<Decimal> discounts = orderDiscountsMap.get(orderId);
            Decimal currentAdjustment = orderPriceAdjustments.get(orderId) != null ? orderPriceAdjustments.get(orderId) : 0;
            for (Decimal discount : discounts) {
                if (discount < 1.0) {
                    currentAdjustment *= (1 - discount);
                } else {
                    currentAdjustment -= (discount / discounts.size());
                }
            }

            orderPriceAdjustments.put(orderId, currentAdjustment);
        }


        List<PricebookEntry> pricebookEntries = [
                SELECT Id, Pricebook2Id, Product2Id
                FROM PricebookEntry
                WHERE Product2Id = :Utils.PRODUCT.IDS.ComplaintProduct
                AND Pricebook2Id = :Utils.PRICE_BOOK.IDS.MomentumEvents
                LIMIT 1
        ];

        Map<Id, Order> orderMap = new Map<Id, Order>([
                SELECT Id, Final_Price__c, Pricebook2Id, Status
                FROM Order
                WHERE Id IN :orderPriceAdjustments.keySet()
        ]);

        for(Order order : orderMap.values()) {
            if(order.Status != Utils.ORDER.STATUS.Draft) {
                order.Status = Utils.ORDER.STATUS.Draft;
            }
        }

        if(!orderMap.values().isEmpty()) {
            update orderMap.values();
        }


        List<Order> ordersToUpdate = new List<Order>();
        List<OrderItem> orderItemsToInsert = new List<OrderItem>();

        for (Id orderId : orderPriceAdjustments.keySet()) {
            Decimal adjustment = orderPriceAdjustments.get(orderId) * -1;
            Order order = orderMap.get(orderId);

            OrderItem orderItem = new OrderItem(
                    OrderId = orderId,
                    PricebookEntryId = pricebookEntries.get(0).Id,
                    Quantity = 1,
                    UnitPrice = adjustment
            );
            orderItemsToInsert.add(orderItem);

            ordersToUpdate.add(new Order(
                    Id = orderId,
                    Status = Utils.ORDER.STATUS.Activated,
                    Final_Price__c = order.Final_Price__c + adjustment
            ));
        }

        try {
            if (!orderItemsToInsert.isEmpty()) {
                insert orderItemsToInsert;
            }
            if (!ordersToUpdate.isEmpty()) {
                update ordersToUpdate;
            }
        } catch (Exception e) {
            System.debug('Error updating Order or OrderItems: ' + e.getMessage());
            throw new HandledException(e.getMessage());
        }
    }
}