src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Field has an identifier for a case from target org.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Notification__e/Case_Notification__e.object-meta.xml
<CustomObject>
    <label>Case Notification</label>
    <pluralLabel>Case Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Notification__e/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Notification__e/fields/ProductIds__c.field-meta.xml
<CustomField>
    <fullName>ProductIds__c</fullName>
    <label>ProductIds</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/Case_Product__c.object-meta.xml
<CustomObject>
    <label>Case Product</label>
    <nameField>
        <label>Case Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Product__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in integration allow to determine if product was created in this org or was saved from external source.</description>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Case/CaseService.cls
/**
 * Created by patryk.witkowski_bri on 5/19/2025.
 */

public with sharing class CaseService {
    public static CaseResponseDTO createCaseAndPublishEvent(CaseEventDTO caseData) {
        CaseResponseDTO caseResponseDTO = new CaseResponseDTO();

        Case caseToInsert = new Case(
                Subject = caseData.subject,
                Description = caseData.description,
                Status = 'New',
                Origin = 'Web',
                Priority = caseData.priority
        );

        insert caseToInsert;

        caseResponseDTO.caseId = caseToInsert.Id;
        caseResponseDTO.containsExternal = false;
        List<Case_Product__c> caseProducts = new List<Case_Product__c>();

        String productIds = '';

        for(Product2 product : caseData.selectedItems) {
            Case_Product__c caseProduct = new Case_Product__c(
                    Case__c = caseToInsert.Id,
                    Product__c = product.Id
            );
            if(product.IsExternal__c) {
                productIds += product.ExternalId__c + ',';
            }
            caseProducts.add(caseProduct);
        }

        insert caseProducts;

        if(!String.isBlank(productIds)) {
            Case_Notification__e caseNotification = new Case_Notification__e();
            caseNotification.Subject__c = caseData.subject;
            caseNotification.Description__c = caseData.description;
            caseNotification.ExternalId__c = caseToInsert.Id;
            caseNotification.ProductIds__c = productIds.removeEnd(',');
            caseNotification.Priority__c = caseData.priority;

            System.enqueueJob(new CaseExternalQueueable(caseNotification));
            caseResponseDTO.containsExternal = true;
        }
        return caseResponseDTO;
    }

    public class CaseEventDTO {
        @AuraEnabled public String orderId { set; get; }
        @AuraEnabled public String subject { set; get; }
        @AuraEnabled public String priority { set; get; }
        @AuraEnabled public String description { set; get; }
        @AuraEnabled public List<Product2> selectedItems { set; get; }
    }

    public class CaseResponseDTO {
        @AuraEnabled public String caseId { set; get; }
        @AuraEnabled public Boolean containsExternal { set; get; }
    }
}