src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Product__c/Case_Product__c.object-meta.xml
<CustomObject>
    <label>Case Product</label>
    <nameField>
        <label>Case Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Product__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Return_percentage__c.field-meta.xml
<CustomField>
    <fullName>Return_percentage__c</fullName>
    <description>Enter percent of value you want to return to client.</description>
    <label>Return percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full refund</fullName>
            </value>
            <value>
                <fullName>Partially refund</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test/Data/Builder/CaseProductBuilder.cls
/**
 * Created by patryk.witkowski_bri on 5/28/2025.
 */

public class CaseProductBuilder {
    private final Case_Product__c caseProduct;

    public CaseProductBuilder() {
        this.caseProduct = new Case_Product__c();
    }

    public CaseProductBuilder orderItem(String orderItemId) {
        this.caseProduct.Order_Product__c = orderItemId;
        return this;
    }

    public CaseProductBuilder name(String name) {
        this.caseProduct.Name = name;
        return this;
    }

    public CaseProductBuilder product(String productId) {
        this.caseProduct.Product__c = productId;
        return this;
    }

    public CaseProductBuilder case(String caseId) {
        this.caseProduct.Case__c = caseId;
        return this;
    }

    public CaseProductBuilder status(String status) {
        this.caseProduct.Status__c = status;
        return this;
    }

    public CaseProductBuilder strategy(String strategy) {
        this.caseProduct.Strategy__c = strategy;
        return this;
    }

    public CaseProductBuilder returnPercentage(Integer percentage) {
        this.caseProduct.Return_percentage__c = percentage;
        return this;
    }

    public CaseProductBuilder save() {
        insert this.caseProduct;
        return this;
    }

    public Case_Product__c build() {
        return this.caseProduct;
    }
}