src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Field has an identifier for a case from target org.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/Case_Product__c.object-meta.xml
<CustomObject>
    <label>Case Product</label>
    <nameField>
        <label>Case Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Product__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Return_percentage__c.field-meta.xml
<CustomField>
    <fullName>Return_percentage__c</fullName>
    <description>Enter percent of value you want to return to client.</description>
    <label>Return percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full refund</fullName>
            </value>
            <value>
                <fullName>Partially refund</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Product_Approval__e/Case_Product_Approval__e.object-meta.xml
<CustomObject>
    <label>Case Product Approval</label>
    <pluralLabel>Case Products Approval</pluralLabel>
</CustomObject>

force-app/main/default/classes/Test/Actions/TA_CaseProduct_ApprovalEvent_Test.cls
/**
 * Created by patryk.witkowski_bri on 5/28/2025.
 */

@IsTest
private class TA_CaseProduct_ApprovalEvent_Test {

    @TestSetup
    static void setup() {
        new DataGenerator().createData();
    }

    @IsTest
    static void caseProductsShouldBeUpdated_Success() {
        List<Case> cases = [SELECT Id FROM Case];
        List<Product2> products = [SELECT Id, ExternalId__c FROM Product2];

        List<Case_Product_Approval__e> caseProductApprovals = new List<Case_Product_Approval__e>();
        Case_Product_Approval__e caseProductApproval = new DataGenerator().createCaseProductApproval(cases.get(0).Id, products.get(0).Id);
        caseProductApprovals.add(caseProductApproval);

        Test.startTest();
        EventBus.publish(caseProductApproval);
        Test.stopTest();

        for(Case_Product__c caseProduct : [SELECT Id, Name, Case__c, Product__c, Return_percentage__c, Strategy__c, Status__c, Description__c FROM Case_Product__c]) {
            Assert.areEqual(10, caseProduct.Return_percentage__c, 'Return percentage should be 10');
            Assert.areEqual('success', caseProduct.Description__c, 'Description should be changed to success');
        }
    }


    class DataGenerator extends Factory {
        public Product2 createExternalProduct() {
            Product2 product = prepareProduct()
                    .external(true)
                    .externalId(UUID.randomUUID().toString())
                    .save()
                    .build();
            return product;
        }


        public Case_Product_Approval__e createCaseProductApproval(String caseId, String productId) {
            Case_Product_Approval__e caseProductApproval = prepareCaseProductApproval()
                    .case(caseId)
                    .product(productId)
                    .approvalStatus('[{"productId":"'+productId+'","data":{"strategy":"Partially refund","status":"Approved","percentage":10,"description":"success"},"caseId":"'+caseId+'"}]')
                    .build();
            return caseProductApproval;
        }

        public Case_Product__c createCaseProducts(String caseId, String productId) {
            Case_Product__c caseProduct = prepareCaseProduct()
                    .product(productId)
                    .case(caseId)
                    .save()
                    .build();
            return caseProduct;
        }

        public override void createData() {
            createPricebook();
            Case cases = createCase();
            Product2 product = createExternalProduct();
            product.ExternalId__c = product.Id;
            update product;
            createCaseProducts(cases.Id, product.Id);
        }
    }
}