src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Final_Price__c</fullName>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partly paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Total_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount__c</fullName>
    <label>Total Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Discount__c/Order_Discount__c.object-meta.xml
<CustomObject>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Order Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Order Discounts</relationshipLabel>
    <relationshipName>Order_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Discount__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Discounts</relationshipLabel>
    <relationshipName>Order_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in integration allow to determine if product was created in this org or was saved from external source.</description>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Order/OrderService.cls
/**
 * Created by patryk.witkowski_bri on 4/29/2025.
 */

public with sharing class OrderService {
    public static void createOrder(Id opportunityId, List<ProductOrderDTO> products, Decimal discount, List<Id> discountIds) {
            List<Opportunity> opportunity = [
                    SELECT AccountId, Event_Date__c, Event_Address__Street__s, Event_Address__City__s, Event_Address__CountryCode__s, Event_Address__StateCode__s, Event_Address__PostalCode__s
                    FROM Opportunity
                    WHERE Id = :opportunityId
                    LIMIT 1
            ];

            if (opportunity.isEmpty()) {
                throw new AuraHandledException(Utils.OPPORTUNITY.ERRORS.OpportunityNotExist);
            }

            Order order = new Order(
                    AccountId = opportunity.get(0).AccountId,
                    Event_Date__c = opportunity.get(0).Event_Date__c,
                    Event_Address__Street__s = opportunity.get(0).Event_Address__Street__s,
                    Event_Address__City__s = opportunity.get(0).Event_Address__City__s,
                    Event_Address__CountryCode__s = opportunity.get(0).Event_Address__CountryCode__s,
                    Event_Address__PostalCode__s = opportunity.get(0).Event_Address__PostalCode__s,
                    Event_Address__StateCode__s = opportunity.get(0).Event_Address__StateCode__s,
                    Status = 'Draft',
                    OpportunityId = opportunityId,
                    Pricebook2Id = Id.valueOf(Utils.PRICE_BOOK.IDS.MomentumEvents),
                    EffectiveDate = Date.today(),
                    Payment_Status__c = 'Waiting'
            );

            insert order;

            Set<Id> productIds = new Set<Id>();

            List<Order_Discount__c> orderDiscounts = new List<Order_Discount__c>();

            for (Id discountId : discountIds) {
                Order_Discount__c orderDiscount = new Order_Discount__c();
                orderDiscount.Order__c = order.Id;
                orderDiscount.Discount__c = discountId;
                orderDiscounts.add(orderDiscount);
            }

            insert orderDiscounts;

            for (ProductOrderDTO product : products) {
                productIds.add(Id.valueOf(product.productId));
            }
            List<PricebookEntry> pricebookEntries = [
                    SELECT Id, UnitPrice, Product2Id
                    FROM PricebookEntry
                    WHERE Pricebook2Id = :Id.valueOf(Utils.PRICE_BOOK.IDS.MomentumEvents)
                    AND Product2Id IN :productIds
                    AND IsActive = TRUE
            ];

            List<OrderItem> orderItems = new List<OrderItem>();

            for (PricebookEntry pricebookEntry : pricebookEntries) {
                OrderItem orderItem = new OrderItem(
                        UnitPrice = pricebookEntry.UnitPrice,
                        PricebookEntryId = pricebookEntry.Id,
                        Quantity = 1,
                        OrderId = order.Id
                );
                orderItems.add(orderItem);
            }

            insert orderItems;

            List<Order> orderToUpdate = [
                    SELECT Status, Total_Discount__c, TotalAmount
                    FROM Order
                    WHERE Id = :order.Id
            ];

            if (orderToUpdate.isEmpty()) {
                throw new AuraHandledException(Utils.ORDER.ERRORS.FailedUpdate);
            }

            orderToUpdate.get(0).Status = 'Activated';
            orderToUpdate.get(0).Total_Discount__c = discount;
            orderToUpdate.get(0).Final_Price__c = orderToUpdate.get(0).TotalAmount - discount;

            update orderToUpdate.get(0);

            opportunity.get(0).StageName = 'Closed Won';

            update opportunity.get(0);
    }

    public static List<Product2> getProducts(String orderId) {
        List<OrderItem> orderItems = [SELECT Product2Id FROM OrderItem WHERE OrderId = :orderId];

        Set<Id> productIds = new Set<Id>();

        for(OrderItem orderItem : orderItems) {
            productIds.add(orderItem.Product2Id);
        }

        return [SELECT Id, Name, Base_Price__c, IsExternal__c, ExternalId__c FROM Product2 WHERE Id IN :productIds];
    }

    public class ProductOrderDTO {
        @AuraEnabled public String productId { get; set; }
        @AuraEnabled public String category { get; set; }
        @AuraEnabled public String price { get; set; }
    }
}