src/objects/Order.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Discount__c/Order_Discount__c.object-meta.xml
<CustomObject>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Order Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Order Discounts</relationshipLabel>
    <relationshipName>Order_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Discount__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Discounts</relationshipLabel>
    <relationshipName>Order_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test/Data/Builder/OrderDiscountBuilder.cls
/**
 * Created by patryk.witkowski_bri on 5/30/2025.
 */

public class OrderDiscountBuilder {
    private final Order_Discount__c orderDiscount;

    public OrderDiscountBuilder() {
        this.orderDiscount = new Order_Discount__c();
    }

    public OrderDiscountBuilder order(String orderId) {
        this.orderDiscount.Order__c = orderId;
        return this;
    }

    public OrderDiscountBuilder discount(String discountId) {
        this.orderDiscount.Discount__c = discountId;
        return this;
    }

    public OrderDiscountBuilder save() {
        insert orderDiscount;
        return this;
    }

    public Order_Discount__c build() {
        return this.orderDiscount;
    }


}