src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in integration allow to determine if product was created in this org or was saved from external source.</description>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test/Integration/TA_Product_CreateTest.cls
/**
 * Created by patryk.witkowski_bri on 5/9/2025.
 */
@IsTest
private class TA_Product_CreateTest {
    @IsTest
    static void testAfterInsertSuccess() {
        Product2 prod1 = new Product2(
                Name = 'Test Product 1',
                ProductCode = 'TEST001',
                Base_Price__c = 100.00,
                IsActive = true,
                IsExternal__c = false
        );
        Product2 prod2 = new Product2(
                Name = 'Test Product 2',
                ProductCode = 'TEST002',
                Base_Price__c = 200.00,
                IsActive = true,
                IsExternal__c = false
        );
        List<Product2> products = new List<Product2>{prod1, prod2};

        Test.startTest();
        insert products;
        Test.stopTest();

        List<Product2> products2 = [
                SELECT Id, ExternalId__c, IsExternal__c
                FROM Product2
        ];

        Assert.areEqual(2, products2.size(), 'Two products should be inserted');
        for (Product2 entry : products2) {
            Assert.areEqual(false, entry.IsExternal__c, 'Product shouldn\'t be from external source');
            Assert.areEqual(true, String.isNotBlank(entry.ExternalId__c), 'Product should have ExternalId');
        }
    }
}