src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in integration allow to determine if product was created in this org or was saved from external source.</description>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Integration/Trigger/TA_Product_Delete.cls
/**
 * Created by patryk.witkowski_bri on 5/8/2025.
 */

public class TA_Product_Delete implements TriggerAction.BeforeDelete {
    public void beforeDelete(List<Product2> triggerOld) {
        List<Product2> products = [
                SELECT Id, Name, IsActive, ExternalId__c
                FROM Product2
                WHERE Id IN :triggerOld AND IsExternal__c = FALSE
        ];

        for(Product2 product : products) {
            product.IsActive = false;
        }

        if(!products.isEmpty()) {
            update products;
        }
    }
}