src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in integration allow to determine if product was created in this org or was saved from external source.</description>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Integration/Trigger/TA_Product_Update.cls
/**
 * Created by patryk.witkowski_bri on 5/8/2025.
 */

public class TA_Product_Update implements TriggerAction.AfterUpdate {
    public void afterUpdate(List<Product2> triggerNew, List<Product2> triggerOld) {
        Set<Id> productIds = new Set<Id>();

        for(Product2 product : triggerOld) {
            if(!product.IsExternal__c) {
                productIds.add(product.Id);
            }
        }

        try {
            if(!productIds.isEmpty()) {
                IntegrationCallout.updateProducts(productIds);
            }
        } catch (Exception ex) {
            throw new AuraHandledException('Cant update the record');
        }


        List<PricebookEntry> pricebookEntries = [
                SELECT UnitPrice, Product2.Base_Price__c
                FROM PricebookEntry
                WHERE Product2Id IN : triggerOld
        ];

        for(PricebookEntry pricebookEntry : pricebookEntries) {
            pricebookEntry.UnitPrice = pricebookEntry.Product2.Base_Price__c;
        }

        update pricebookEntries;
    }
}