src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Logger__c/Product_Logger__c.object-meta.xml
<CustomObject>
    <label>Product Logger</label>
    <nameField>
        <label>Product Logger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Logger__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Logger</relationshipLabel>
    <relationshipName>Products_Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <label>Retry</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Integration/Batch/ProductFailedBatch.cls
/**
 * Created by patryk.witkowski_bri on 5/14/2025.
 */

public with sharing class ProductFailedBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
                SELECT Id, Product__c, Method__c, Retry__c, Status__c
                FROM Product_Logger__c
                WHERE Status__c = :Utils.LOG.STATUS.FAILED AND Retry__c < 3 AND Type__c = :Utils.LOG.TYPE.CALLOUT
        ]);
    }

    public void finish(Database.BatchableContext context) {
    }

    public void execute(Database.BatchableContext context, List<SObject> records) {
        List<Id> productIds = new List<Id>();
        for(Product_Logger__c productLogger : (List<Product_Logger__c>) records) {
            productIds.add(productLogger.Product__c);
        }


        Map<Id, Product2> productMap = new Map<Id, Product2>([
                SELECT Id, Name, ProductCode, Base_Price__c, IsActive, ExternalId__c
                FROM Product2
                WHERE Id IN :productIds
        ]);

        for(Product_Logger__c productLogger : (List<Product_Logger__c>) records) {
            try {
                Http http = new Http();
                HttpRequest request = HttpConfiguration.configureRequest(productLogger.Method__c, new List<Product2>{productMap.get(productLogger.Product__c)});
                HttpResponse response = http.send(request);

                List<Logger.ProductLog> productLogs = (List<Logger.ProductLog>) JSON.deserialize(response.getBody(), List<Logger.ProductLog>.class);
                if(productLogs.get(0).status == 'Failed') {
                    productLogger.Retry__c += 1;
                } else {
                    productLogger.Status__c = productLogs.get(0).status;
                }
            } catch (Exception ex) {
                System.debug(ex.getMessage());
            }
        }

        try {
            update records;
        } catch (Exception ex) {
            System.debug('THERE IS AN ERROR!');
        }
    }
}