src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in integration allow to determine if product was created in this org or was saved from external source.</description>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Integration/Trigger/TA_Product_BeforeCreate.cls
/**
 * Created by patryk.witkowski_bri on 5/8/2025.
 */

public with sharing class TA_Product_BeforeCreate implements TriggerAction.BeforeInsert {
    public void beforeInsert(List<Product2> triggerNew) {
        for(Product2 product : triggerNew) {
            if(!product.IsExternal__c && String.isBlank(product.ExternalId__c)) {
                product.ExternalId__c = UUID.randomUUID().toString();
            }
        }
    }
}