src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in integration allow to determine if product was created in this org or was saved from external source.</description>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Integration/Trigger/TA_Product_Create.cls
/**
 * Created by patryk.witkowski_bri on 5/8/2025.
 */

public class TA_Product_Create implements TriggerAction.AfterInsert {
    public void afterInsert(List<Product2> triggerNew) {
        List<Id> productsId = new List<Id>();

        for(Product2 product : triggerNew) {
            if(!product.IsExternal__c) {
                productsId.add(product.Id);
            }
        }

        try {
            if(!productsId.isEmpty()) {
                IntegrationCallout.sendProducts(productsId);
            }
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }

        String PriceBookId = Utils.PRICE_BOOK.IDS.MomentumEvents;

        List<PricebookEntry> pricebookStandardEntries = new List<PricebookEntry>();
        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();

        List<Pricebook2> standardPriceBook = [
                SELECT Id
                FROM Pricebook2
                WHERE IsStandard = TRUE
        ];

        for(Product2 product : triggerNew) {
            PricebookEntry pricebookEntry = new PricebookEntry();
            pricebookEntry.IsActive = product.IsActive;
            pricebookEntry.Pricebook2Id = standardPriceBook.get(0).Id;
            pricebookEntry.Product2Id = product.Id;
            pricebookEntry.UnitPrice = product.Base_Price__c;
            pricebookStandardEntries.add(pricebookEntry);
        }

        insert pricebookStandardEntries;

        for(Product2 product : triggerNew) {
            PricebookEntry pricebookEntry = new PricebookEntry();
            pricebookEntry.IsActive = product.IsActive;
            pricebookEntry.Pricebook2Id = PriceBookId;
            pricebookEntry.Product2Id = product.Id;
            pricebookEntry.UnitPrice = product.Base_Price__c;
            pricebookEntries.add(pricebookEntry);
        }

        insert pricebookEntries;
    }
}