force-app/main/default/objects/Case_Product__c/Case_Product__c.object-meta.xml
<CustomObject>
    <label>Case Product</label>
    <nameField>
        <label>Case Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Product__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Case_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Return_percentage__c.field-meta.xml
<CustomField>
    <fullName>Return_percentage__c</fullName>
    <description>Enter percent of value you want to return to client.</description>
    <label>Return percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Product__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full refund</fullName>
            </value>
            <value>
                <fullName>Partially refund</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Product_Approval__e/Case_Product_Approval__e.object-meta.xml
<CustomObject>
    <label>Case Product Approval</label>
    <pluralLabel>Case Products Approval</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Product_Approval__e/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Actions/TA_CaseProduct_ApprovalEvent.cls
/**
 * Created by patryk.witkowski_bri on 5/23/2025.
 */

public with sharing class TA_CaseProduct_ApprovalEvent implements TriggerAction.AfterInsert {
    public void afterInsert(List<Case_Product_Approval__e> triggerNew) {
        List<Wrapper> events = new List<Wrapper>();

        for(Case_Product_Approval__e caseProductApproval : triggerNew) {
            List<Wrapper> caseProductApprovalJSON = (List<Wrapper>) JSON.deserialize(caseProductApproval.Approval_Status__c.toString(), List<Wrapper>.class);
            events.add(caseProductApprovalJSON.get(0));
        }

        Set<Id> caseIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        for (Wrapper wrapper : events) {
                if (String.isNotBlank(wrapper.caseId)) {
                    caseIds.add((Id) wrapper.caseId);
                }
                if (String.isNotBlank(wrapper.productId)) {
                    productIds.add((Id) wrapper.productId);
                }
        }

        Map<String, Id> externalIdToProductId = new Map<String, Id>();
        if (!productIds.isEmpty()) {
            List<Product2> products = [
                        SELECT Id, ExternalId__c
                        FROM Product2
                        WHERE ExternalId__c IN :productIds
                ];

                for (Product2 product : products) {
                    externalIdToProductId.put(product.ExternalId__c, product.Id);
                }
        }

        Map<Id, Case_Product__c> caseProductMap = new Map<Id, Case_Product__c>();
        if (!caseIds.isEmpty()) {
                caseProductMap = new Map<Id, Case_Product__c>([
                        SELECT Id, Name, Product__c, Case__c, Status__c, Strategy__c
                        FROM Case_Product__c
                        WHERE Case__c IN :caseIds AND Product__c IN :externalIdToProductId.values()
                ]);
        }

        for (Wrapper wrapper : events) {
                Id caseId = (Id) wrapper.caseId;
                Id productId = externalIdToProductId.get(wrapper.productId);

                for (Case_Product__c caseProduct : caseProductMap.values()) {
                    if (caseProduct.Case__c == caseId && caseProduct.Product__c == productId) {
                        caseProductMap.get(caseProduct.Id).Strategy__c = wrapper.data?.strategy;
                        caseProductMap.get(caseProduct.Id).Status__c = wrapper.data?.status;
                        caseProductMap.get(caseProduct.Id).Description__c = wrapper.data?.description;
                        caseProductMap.get(caseProduct.Id).Return_percentage__c = wrapper.data?.percentage;
                        break;
                    }
                }
        }

        if (!caseProductMap.isEmpty()) {
                update caseProductMap.values();
        }
    }

    class Wrapper {
        public String productId;
        public String caseId;
        public Data data;
    }

    class Data {
        public String strategy;
        public String status;
        public Decimal percentage;
        public String description;
    }
}