force-app/main/default/objects/Discount__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <label>Discount Percentage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Discount/Aura/Combine/PercentageOrderDiscountDecorator.cls
/**
 * Created by patryk.witkowski_bri on 4/28/2025.
 */

public class PercentageOrderDiscountDecorator extends OrderDiscountDecorator {
    private final Discount__c discount;

    public PercentageOrderDiscountDecorator(DiscountCalculator discountCalculator, Discount__c discount) {
        super(discountCalculator);
        this.discount = discount;
    }

    public override Decimal calculateDiscount() {
        Decimal basePrice = discountCalculator.calculateDiscount();
        return basePrice - (basePrice * discount.Discount_Percentage__c / 100);
    }
}