force-app/main/default/objects/Discount__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Discount/Aura/Combine/FixedAmountOrderDiscountDecorator.cls
/**
 * Created by patryk.witkowski_bri on 4/28/2025.
 */

public class FixedAmountOrderDiscountDecorator extends OrderDiscountDecorator {
    private final Discount__c discount;

    public FixedAmountOrderDiscountDecorator(DiscountCalculator discountCalculator, Discount__c discount) {
        super(discountCalculator);
        this.discount = discount;
    }

    public override Decimal calculateDiscount() {
        Decimal basePrice = discountCalculator.calculateDiscount();
        return basePrice - discount.Discount_Amount__c;
    }
}