force-app/main/default/objects/Product_Logger__c/Product_Logger__c.object-meta.xml
<CustomObject>
    <label>Product Logger</label>
    <nameField>
        <label>Product Logger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Logger__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Logger</relationshipLabel>
    <relationshipName>Products_Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <label>Retry</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test/Integration/Email/EmailRetryTest.cls
/**
 * Created by patryk.witkowski_bri on 5/16/2025.
 */

@IsTest
private class EmailRetryTest {
    @TestSetup
    static void setup() {
        new DataGenerator().createData();
    }

    @IsTest
    static void testSendEmailWithMultipleRecords() {
        List<Product_Logger__c> loggers = [
                SELECT Id, Product__c, Method__c, Retry__c, Status__c
                FROM Product_Logger__c
                WHERE Retry__c >= 3
        ];

        RetryEmail retryEmail = new RetryEmail(loggers);

        Test.startTest();
        retryEmail.sendEmail();
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();

        Assert.areEqual(1, invocations, 'Only one email should be sent');
    }

    class DataGenerator extends Factory {

        public override Pricebook2 createPricebook() {
            Pricebook2 pricebook = preparePricebook()
                    .name('Event Management Price Book')
                    .active(true)
                    .save()
                    .build();
            return pricebook;
        }

        public Product_Logger__c createProductLoggerWithProduct(String productId) {
            Product_Logger__c productLogger = prepareProductLogger()
                    .method('POST')
                    .productId(productId)
                    .retry(4)
                    .status('Failed')
                    .save()
                    .build();

            return productLogger;
        }

        public override void createData() {
            createPricebook();
            Id productId = createProduct().Id;
            createProductLoggerWithProduct(productId);
        }
    }
}