force-app/main/default/objects/Product_Logger__c/Product_Logger__c.object-meta.xml
<CustomObject>
    <label>Product Logger</label>
    <nameField>
        <label>Product Logger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Logger__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Logger</relationshipLabel>
    <relationshipName>Products_Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <label>Retry</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test/Data/Builder/ProductLoggerBuilder.cls
/**
 * Created by patryk.witkowski_bri on 5/16/2025.
 */

public class ProductLoggerBuilder {

    private final Product_Logger__c productLogger;

    public ProductLoggerBuilder() {
        this.productLogger = new Product_Logger__c();
    }

    public ProductLoggerBuilder retry(Integer retry) {
        this.productLogger.Retry__c = retry;
        return this;
    }

    public ProductLoggerBuilder method(String method) {
        this.productLogger.Method__c = method;
        return this;
    }

    public ProductLoggerBuilder status(String status) {
        this.productLogger.Status__c = status;
        return this;
    }

    public ProductLoggerBuilder type(String type) {
        this.productLogger.Type__c = type;
        return this;
    }

    public ProductLoggerBuilder productId(String productId) {
        this.productLogger.Product__c = productId;
        return this;
    }

    public ProductLoggerBuilder save() {
        insert this.productLogger;
        return this;
    }

    public Product_Logger__c build() {
        return this.productLogger;
    }
}