force-app/main/default/objects/Product_Logger__c/Product_Logger__c.object-meta.xml
<CustomObject>
    <label>Product Logger</label>
    <nameField>
        <label>Product Logger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Logger__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Logger</relationshipLabel>
    <relationshipName>Products_Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <label>Retry</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Logger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Integration/Log/Logger.cls
/**
 * Created by patryk.witkowski_bri on 5/13/2025.
 */

public with sharing class Logger {

    public static void logProductCallout(List<ProductLog> productLogs, String method) {
        List<Product_Logger__c> productLoggers = new List<Product_Logger__c>();

        for (ProductLog product : productLogs) {
            Product_Logger__c productLogger = new Product_Logger__c();
            productLogger.Timestamp__c = Datetime.now();
            productLogger.Product__c = product.recordId;
            productLogger.Request_Body__c = product.requestBody;
            productLogger.Response_Body__c = JSON.serialize(product.responseBody);
            productLogger.Status__c = (String) product.responseBody.get(0).status;
            productLogger.Type__c = 'Callout';
            productLogger.Retry__c = product.responseBody.get(0).status == 'Failed' ? 1 : null;
            productLogger.Method__c = method;
            productLogger.Name = product.recordId + ' ' + Datetime.now();
            productLoggers.add(productLogger);
        }
        insert productLoggers;
    }

    public static void logProductRest(List<ProductLog> productLogs, String method) {
        List<Product_Logger__c> productLoggers = new List<Product_Logger__c>();

        for(ProductLog product : productLogs) {
            Product_Logger__c productLogger = new Product_Logger__c();
            productLogger.Timestamp__c = Datetime.now();
            productLogger.Product__c = product.recordId;
            productLogger.Request_Body__c = product.requestBody;
            productLogger.Response_Body__c = JSON.serialize(product.responseBody);
            productLogger.Status__c = (String) product.responseBody.get(0).status;
            productLogger.Type__c = 'REST';
            productLogger.Method__c = method;
            productLogger.Name = product.recordId + ' ' + Datetime.now();
            productLoggers.add(productLogger);
        }
        insert productLoggers;
    }

    public static ResponseDTO responseBodyReturn(String recordId, Boolean isSuccess, String message) {
        ResponseDTO responseDTO = new ResponseDTO();
        responseDTO.recordId = recordId;
        if(isSuccess) {
            responseDTO.status = Utils.LOG.STATUS.SUCCESS;
            responseDTO.message = message;
        } else {
            responseDTO.status = Utils.LOG.STATUS.FAILED;
            responseDTO.message = message;
        }
        return responseDTO;
    }

    public class ProductLog {
        public String recordId {get; set;}
        public String requestBody {get; set;}
        public List<ResponseDTO> responseBody {get; set;}
        public String status {get; set;}
        public String method {get; set;}
    }

    public class ResponseDTO {
        public String message {get; set;}
        public String recordId {get; set;}
        public String status {get; set;}
    }
}